# Generated by Django 5.2.6 on 2025-09-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='created_at',
        ),
    ]
