pipeline {
    agent any

    environment {
        // Virtual environment path
        VENV_PATH = "${WORKSPACE}/venv"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',   // my GitHub Jenkins credentials ID
                    url: 'https://github.com/ochiengsodhiambo/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv ${VENV_PATH}
                . ${VENV_PATH}/bin/activate
                python3 -m pip install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . ${VENV_PATH}/bin/activate
                pytest messaging_app --maxfail=1 --disable-warnings -q --junitxml=test-results.xml
                '''
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'test-results.xml'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            sh 'rm -rf ${VENV_PATH}'
        }
        success {
            echo ' Build and tests completed successfully!'
        }
        failure {
            echo ' Build failed. Check test logs for details.'
        }
    }
}
